# Generated by Django 2.0.1 on 2018-06-16 18:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('surveying', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=50, null=True)),
                ('lon', models.FloatField(max_length=50, null=True)),
                ('ele', models.FloatField(max_length=50, null=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='exampledata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=50, null=True)),
                ('lon', models.FloatField(max_length=50, null=True)),
                ('ang', models.FloatField(max_length=50, null=True)),
                ('distance', models.FloatField(max_length=50, null=True)),
                ('ele', models.FloatField(max_length=50, null=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
