# Generated by Django 2.0.1 on 2018-06-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveying', '0002_data_exampledata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='datanew',
        ),
    ]
