# Generated by Django 2.0.1 on 2018-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveying', '0004_auto_20180617_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampledata',
            name='totaldistance',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
